### ISSUE TITLE
Binance Api Key

### ISSUE THREAD

**Issue by merolaika** [ekin-kar/ekoPortfolio#1]
Hello, where do we need to add binance api key and secret fields? Can you help with the subject? Şimdiden teşekkürler. :)

**Comment by ekin-kar** [comment]
Hello, thank you for opening an issue. 
I couldn't find time to finish the login logic but you can create an .env.local file and add your keys there.
API_KEY and API_SECRET are the variables names that I used, you can see them in src/lib/binanceUtils.js 
Hope that helps.

**Comment by merolaika** [comment]
Thank you very much for your interest and help. I wish you continued success
